import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
          <body className="bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-gray-50 min-h-screen">
            <header className="w-full py-6 flex justify-center border-b border-gray-200 dark:border-gray-800 mb-8">
              <h1 className="text-3xl font-bold tracking-tight">Pokédex</h1>
            </header>
            {children}
            <footer className="w-full py-4 flex justify-center border-t border-gray-200 dark:border-gray-800 mt-8 text-sm opacity-70">
              <span>Powered by Next.js & PokéAPI</span>
            </footer>
          </body>
        </html>
  );
}
